defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: appname_development

test:
  <<: *defaults
  database: appname_test
  
production:
  <<: *defaults
  database: appname_prods